server:
  port: 0
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
spring:
  application:
    name: device-configuration-service

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
