server:
  port: 12345
spring:
  datasource:
    username: 'ossama'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/inventory
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost